name: Check
on: push
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
           python-version: 3.10.12
      - name: setup pyenv
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: 3.10.12
      - name: install poetry
        uses: Gr1N/setup-poetry@v8
      - run: poetry --version
      - run: poetry add pytest
      - name: Run tests
        run: poetry run pytest my_tests.py